version: '3.8'

services:
  web:
    build: .
    ports:
      - "9999:9999"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - PLEX_URL=
      - PLEX_TOKEN=
      - RADARR_URL=
      - RADARR_API_KEY=
      - MODEL_SERVER=GROQ
      - GROQ_API_KEY=
      - OLLAMA_URL=
      - TZ=Europe/Paris
    command: flask run --host=0.0.0.0 --port=9999
    networks:
      - mynetwork
#    depends_on:
#      - ollama

#  ollama:
#    image: ollama/ollama
#    ports:
#      - "11434:11434"
#    volumes:
#      - ./ollama_data:/root/.ollama
#    networks:
#      - mynetwork

networks:
  mynetwork:
    driver: bridge
